Rails:
  Enabled: true

AllCops:
  Exclude:
    - ./**/config.ru
    - ./**/Rakefile
    - ./**/Gemfile
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - vendor/**/*
    - !ruby/regexp /old_and_unused\.rb$/

Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
